version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "${HTTP_FORWARD_PORT:-80}:80"
      - "${GRPC_FORWARD_PORT:-8080}:8080"
    depends_on:
      - db
    networks:
      - network
    volumes:
      - .:/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-users}"
      PGPORT: "${POSTGRES_PORT:-5432}"
    ports:
      - "${POSTGRES_FORWARD_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  postgres_data:
networks:
  network:
    driver: bridge